######################################################################
#
# File name : accu_tb_simulate.do
# Created on: Sat Jan 23 10:15:46 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -lib xil_defaultlib xil_defaultlib.accu_tb

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {accu_tb_wave.do}

view wave
view structure
view signals

do {accu_tb.udo}

run 20us
