######################################################################
#
# File name : accu_tb.udo
# Created on: Fri Jan 22 21:17:18 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
