# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Master_Thesis/Vivado/HwProj/HwProj.srcs/sources_1/bd/design_1/ip/design_1_ConvAccelerator_0_9/design_1_ConvAccelerator_0_9.xci
# IP: The module: 'design_1_ConvAccelerator_0_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Master_Thesis/Vivado/HwProj/HwProj.srcs/sources_1/bd/design_1/constrs_1/new/my_constrain.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ConvAccelerator_0_9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Master_Thesis/Vivado/HwProj/HwProj.srcs/sources_1/bd/design_1/ip/design_1_ConvAccelerator_0_9/design_1_ConvAccelerator_0_9.xci
# IP: The module: 'design_1_ConvAccelerator_0_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Master_Thesis/Vivado/HwProj/HwProj.srcs/sources_1/bd/design_1/constrs_1/new/my_constrain.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_ConvAccelerator_0_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
