######################################################################
#
# File name : ConvAccelerator_tb_compile.do
# Created on: Fri Jan 29 10:46:18 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/ACCU.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/ALU.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/BRAM_SP.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/ConvAccelerator.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/DIS_RAM_SP.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/MyAccelerator_v2_0_S00_AXI.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/data_buffer.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/dff.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/main_fsm.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/w_sticker.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/weight_buffer.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/tb/ConvAccelerator_tb.vhd" \


quit -force

