######################################################################
#
# File name : bram_dp_tb_simulate.do
# Created on: Sat Jan 23 11:26:06 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -lib xil_defaultlib xil_defaultlib.bram_dp_tb

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {bram_dp_tb_wave.do}

view wave
view structure
view signals

do {bram_dp_tb.udo}

run 20us
