######################################################################
#
# File name : bram_dp_tb_wave.do
# Created on: Sat Jan 23 11:25:53 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
