# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/design_1_system_ila_2_1.xci
# IP: The module: 'design_1_system_ila_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/bd_f66c.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f66c || ORIG_REF_NAME==bd_f66c} -quiet] -quiet

# IP: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/bd_f66c_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] -quiet

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/bd_f66c_ila_lib_0_ooc.xdc

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/bd_f66c_ooc.xdc

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/design_1_system_ila_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_2_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/design_1_system_ila_2_1.xci
# IP: The module: 'design_1_system_ila_2_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/bd_f66c.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f66c || ORIG_REF_NAME==bd_f66c} -quiet] -quiet

# IP: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/bd_f66c_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] -quiet

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f66c_ila_lib_0 || ORIG_REF_NAME==bd_f66c_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/ip/ip_0/bd_f66c_ila_lib_0_ooc.xdc

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/bd_0/bd_f66c_ooc.xdc

# XDC: d:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/dma_test/dma_test.srcs/sources_1/bd/design_1/ip/design_1_system_ila_2_1/design_1_system_ila_2_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_system_ila_2_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
