######################################################################
#
# File name : weight_buffer_tb_compile.do
# Created on: Tue Jan 19 12:32:02 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/LUTRAM_SP.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/w_sticker.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/weight_buffer.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/tb/weight_buffer_tb.vhd" \


quit -force

