######################################################################
#
# File name : weight_buffer_tb_wave.do
# Created on: Mon Jan 18 13:40:02 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
