######################################################################
#
# File name : main_fms_tb_wave.do
# Created on: Tue Jan 19 18:32:54 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
