######################################################################
#
# File name : main_fms_tb_simulate.do
# Created on: Fri Jan 22 12:23:13 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -lib xil_defaultlib xil_defaultlib.main_fms_tb

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {main_fms_tb_wave.do}

view wave
view structure
view signals

do {main_fms_tb.udo}

run 20us
