webtalk_init -webtalk_dir D:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/main_fsm_sim/main_fsm_sim.sim/sim_1/behav/xsim/xsim.dir/main_fms_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jan  2 18:05:04 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "f2d8601f-2ee3-412a-bd84-9388762e460b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c93270160f144a5ab7b1e0bd050e05f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3192 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "21 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7764_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1507086016 -regid "" -xml D:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/main_fsm_sim/main_fsm_sim.sim/sim_1/behav/xsim/xsim.dir/main_fms_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/main_fsm_sim/main_fsm_sim.sim/sim_1/behav/xsim/xsim.dir/main_fms_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Vivado_Project/MS.CnnAccFPGA/Vivado_proj/main_fsm_sim/main_fsm_sim.sim/sim_1/behav/xsim/xsim.dir/main_fms_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
