######################################################################
#
# File name : data_buffer_tb_wave.do
# Created on: Tue Jan 19 12:54:30 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
