######################################################################
#
# File name : w_sticker_tb_wave.do
# Created on: Thu Jan 14 11:21:32 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
