######################################################################
#
# File name : w_sticker_tb_simulate.do
# Created on: Mon Jan 18 13:52:11 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -lib xil_defaultlib xil_defaultlib.w_sticker_tb

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {w_sticker_tb_wave.do}

view wave
view structure
view signals

do {w_sticker_tb.udo}

run 1000ns
