######################################################################
#
# File name : w_sticker_tb_compile.do
# Created on: Mon Jan 18 13:52:10 +0100 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom  -93 -work xil_defaultlib  \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/hdl/w_sticker.vhd" \
"../../../../../../Ip_repo/ip_repo/MyAcc_3.0/tb/w_sticker_tb.vhd" \


quit -force

